insert into public.news_items
  (id, ticker, market, company_name, title, source, url, published_at, raw_summary)
values
  ('00000000-0000-0000-0000-000000000101', 'CSL', 'ASX', 'CSL Limited', 'CSL announces restructuring plan with one-off costs', 'Demo Market News', '#', '2026-05-26 09:00:00+00', 'CSL announced a restructuring plan expected to create near-term costs while targeting operational efficiency.'),
  ('00000000-0000-0000-0000-000000000102', 'BHP', 'ASX', 'BHP Group', 'BHP affected by falling iron ore prices due to weaker China demand', 'Demo Commodities Wire', '#', '2026-05-26 08:30:00+00', 'Iron ore prices fell after weaker China demand indicators, pressuring resource producers.'),
  ('00000000-0000-0000-0000-000000000103', 'CBA', 'ASX', 'Commonwealth Bank of Australia', 'CBA affected by rising interest rate expectations after inflation data', 'Demo Macro Desk', '#', '2026-05-26 07:45:00+00', 'Inflation data lifted interest rate expectations, creating mixed implications for bank margins and credit risk.'),
  ('00000000-0000-0000-0000-000000000104', 'AAPL', 'US', 'Apple Inc.', 'Apple reports stronger-than-expected quarterly earnings', 'Demo US Earnings', '#', '2026-05-25 22:00:00+00', 'Apple reported quarterly earnings ahead of expectations, helped by services and operating discipline.'),
  ('00000000-0000-0000-0000-000000000105', 'NVDA', 'US', 'NVIDIA Corporation', 'Nvidia revenue growth accelerates due to AI chip demand', 'Demo Tech Brief', '#', '2026-05-25 21:15:00+00', 'Nvidia revenue growth accelerated as AI chip demand remained strong across data center customers.'),
  ('00000000-0000-0000-0000-000000000106', 'TENCENT', 'HK', 'Tencent Holdings', 'Tencent faces regulatory uncertainty around online gaming rules', 'Demo Asia Policy', '#', '2026-05-25 10:30:00+00', 'New gaming rule discussion raised uncertainty around monetisation, approvals, and compliance costs.'),
  ('00000000-0000-0000-0000-000000000107', 'DBS', 'SG', 'DBS Group', 'DBS benefits from higher interest rate environment but faces credit cycle risk', 'Demo Singapore Markets', '#', '2026-05-25 09:30:00+00', 'Higher rates may support net interest income, while credit losses could rise if borrowers weaken.'),
  ('00000000-0000-0000-0000-000000000108', 'KWEICHOWMOUTAI', 'CN', 'Kweichow Moutai', 'Kweichow Moutai reports slower revenue growth', 'Demo China Consumer', '#', '2026-05-25 08:00:00+00', 'Kweichow Moutai reported slower revenue growth, raising questions about premium demand momentum.')
on conflict (id) do nothing;

insert into public.ai_analyses
  (id, news_item_id, ticker, market, event_type, theoretical_impact, importance, short_term_impact, long_term_impact, affected_valuation_drivers, dcf_valuation_implication, portfolio_relevance, key_risks, professional_explanation, beginner_friendly_summary, thesis_effect, language)
values
  ('00000000-0000-0000-0000-000000000201', '00000000-0000-0000-0000-000000000101', 'CSL', 'ASX', 'Restructuring', 'Mixed', 'High', 'Mixed or negative in the short term because one-off costs can pressure reported earnings and free cash flow.', 'Positive if execution succeeds and recurring cost savings improve operating margin.', 'One-off costs, operating margin, FCF, execution risk.', 'Short-term FCF may fall due to restructuring costs; long-term value may improve if margins rise.', 'High if the user owns a company in turnaround.', 'Execution failure, cost overrun, staff disruption.', 'Restructuring is short-term pain for possible long-term gain. The key is whether cost savings are real and sustainable.', '简单说，公司现在可能要花钱调整业务，所以短期不好看。但如果调整成功，以后可能更省钱、利润更高。', 'Unclear', 'English'),
  ('00000000-0000-0000-0000-000000000202', '00000000-0000-0000-0000-000000000102', 'BHP', 'ASX', 'Commodity price decline', 'Negative', 'High', 'Negative for producers because lower commodity prices can reduce expected revenue and cash flow.', 'Depends on demand, cost position, and whether commodity prices recover.', 'Revenue, margin, reserves value, FCF.', 'Resource companies may see lower revenue and cash flow forecasts.', 'High for resource stocks.', 'Asset impairment, project delays, dividend cuts.', 'Resource company valuations are highly sensitive to commodity price assumptions.', '简单说，卖资源的公司会因为价格下跌少赚钱；但买资源当原材料的公司可能会省钱。', 'Weakens thesis', 'English'),
  ('00000000-0000-0000-0000-000000000203', '00000000-0000-0000-0000-000000000103', 'CBA', 'ASX', 'Interest rate rise', 'Mixed', 'Medium', 'Rising rates can pressure equity valuations but may support bank net interest income.', 'Long-term impact depends on credit quality, deposit competition, and loan demand.', 'WACC, cost of debt, demand, valuation multiple.', 'Higher discount rates reduce present value of future cash flows.', 'High for growth stocks, REITs, banks, and leveraged companies.', 'Higher financing cost, lower demand, multiple compression.', 'Rising rates pressure valuations, especially for high-growth and leveraged companies.', '简单说，利率上升会让钱变贵，也会让未来利润折现后变得没那么值钱。', 'Unclear', 'English'),
  ('00000000-0000-0000-0000-000000000204', '00000000-0000-0000-0000-000000000104', 'AAPL', 'US', 'Earnings beat', 'Positive', 'High', 'Usually positive when earnings beat market expectations.', 'Positive if driven by sustainable revenue growth, margin improvement, or operating efficiency.', 'Revenue growth, operating margin, EPS, free cash flow, valuation multiple.', 'DCF value may increase if future revenue, margin, or FCF forecasts are raised.', 'High if the user owns the stock and the beat supports the user thesis.', 'One-off gains, aggressive accounting, costs delayed to future periods, market already priced it in.', 'An earnings beat means the company performed better than market expectations. The quality of the beat matters more than the headline number.', '简单说，公司赚得比大家预期多，通常是好消息。但要看它是真的生意变好了，还是只是一次性的特殊收益。', 'Supports thesis', 'English'),
  ('00000000-0000-0000-0000-000000000205', '00000000-0000-0000-0000-000000000105', 'NVDA', 'US', 'Revenue growth acceleration', 'Positive', 'High', 'Usually positive because faster growth can lift expectations.', 'Positive if growth is sustainable and profitable.', 'Revenue growth, market share, operating leverage, free cash flow, terminal growth.', 'Higher revenue growth forecasts increase future cash flow and may increase terminal value.', 'Very high for growth stocks.', 'Low-margin growth, promotion-driven growth, one-off orders, channel stuffing.', 'Faster revenue growth may indicate stronger demand, pricing power, market share gains, or successful new products.', '简单说，公司卖得更多、增长更快，通常是好事。但也要看它是不是为了增长牺牲利润。', 'Supports thesis', 'English'),
  ('00000000-0000-0000-0000-000000000206', '00000000-0000-0000-0000-000000000106', 'TENCENT', 'HK', 'Regulatory risk', 'Mixed', 'High', 'Usually negative or mixed because regulation raises uncertainty.', 'Long-term impact depends on final rules, compliance cost, monetisation limits, and user demand.', 'Legal cost, revenue risk, margin, WACC, valuation multiple.', 'Potential restrictions can reduce cash flow and increase risk premium.', 'High for all shareholders, especially concentrated positions.', 'Fines, business restrictions, customer loss, management change.', 'Legal and regulatory events increase uncertainty and may cause markets to discount worst-case outcomes.', '简单说，公司被起诉或调查，市场会担心它要赔钱、被罚，或者以后做生意受影响。', 'Unclear', 'English'),
  ('00000000-0000-0000-0000-000000000207', '00000000-0000-0000-0000-000000000107', 'DBS', 'SG', 'Interest rate rise for banks', 'Mixed', 'Medium', 'Higher rates may help bank income but can also increase credit risk.', 'Long-term impact depends on deposit costs, loan demand, asset quality, and credit cycle.', 'WACC, cost of debt, demand, valuation multiple.', 'Higher discount rates reduce present value of future cash flows, while bank cash flows may benefit from margin effects.', 'High for banks and rate-sensitive sectors.', 'Higher financing cost, lower demand, credit losses, multiple compression.', 'Rising rates pressure valuations but can affect banks differently through net interest income and credit risk.', '简单说，利率上升对银行可能有利也可能有压力，要同时看利息收入和坏账风险。', 'Unclear', 'English'),
  ('00000000-0000-0000-0000-000000000208', '00000000-0000-0000-0000-000000000108', 'KWEICHOWMOUTAI', 'CN', 'Revenue slowdown', 'Mixed', 'Medium', 'Usually negative because markets reassess growth expectations.', 'Negative if it reflects weaker demand, stronger competition, or market maturity.', 'Revenue growth, market share, operating margin, terminal growth, valuation multiple.', 'Lower revenue growth forecasts reduce future cash flow and may lower terminal growth assumptions.', 'High if user bought the stock for growth.', 'Competition, demand saturation, weaker pricing power.', 'Revenue slowdown makes investors reassess the company growth story, especially for high-valuation growth stocks.', '简单说，公司增长变慢了，市场会担心它以后赚不到之前预期那么多钱。', 'Weakens thesis', 'English')
on conflict (id) do nothing;

insert into public.financial_rules
  (rule_id, category, event_type, typical_short_term_impact, typical_long_term_impact, affected_valuation_drivers, dcf_valuation_implication, professional_logic, key_risks, portfolio_relevance, beginner_friendly_summary)
values
  ('RULE 001', 'Earnings and Revenue', 'Earnings beat', 'Usually positive.', 'Positive if the beat is driven by sustainable revenue growth, margin improvement, or operating efficiency. Less positive if it comes from one-off gains.', 'Revenue growth, operating margin, EPS, free cash flow, valuation multiple.', 'DCF value may increase if future revenue, margin, or FCF forecasts are raised. If the beat is one-off, DCF impact should be limited.', 'An earnings beat means the company performed better than market expectations. The quality of the beat matters more than the headline number.', 'One-off gains, aggressive accounting, costs delayed to future periods, market already priced it in.', 'High if the user owns the stock and the beat supports the user''s investment thesis.', '简单说，公司赚得比大家预期多，通常是好消息。但要看它是真的生意变好了，还是只是一次性的特殊收益。'),
  ('RULE 002', 'Earnings and Revenue', 'Earnings miss', 'Usually negative.', 'Negative if caused by weaker demand, margin pressure, or structural problems. Less negative if caused by temporary factors.', 'Revenue growth, operating margin, EPS, free cash flow, valuation multiple.', 'Future revenue, margin, or FCF forecasts may be lowered, reducing valuation.', 'An earnings miss weakens investor confidence. The key issue is whether the miss is temporary or structural.', 'Repeated misses, guidance downgrade, weak management credibility.', 'High if the user''s thesis depends on earnings recovery.', '简单说，公司表现没大家想得好，短期股价容易受压。关键是看这是一次性问题，还是公司基本面真的变差了。'),
  ('RULE 003', 'Earnings and Revenue', 'Revenue growth acceleration', 'Usually positive.', 'Positive if growth is sustainable and profitable.', 'Revenue growth, market share, operating leverage, free cash flow, terminal growth.', 'Higher revenue growth forecasts increase future cash flow and may increase terminal value.', 'Faster revenue growth may indicate stronger demand, pricing power, market share gains, or successful new products.', 'Low-margin growth, promotion-driven growth, one-off orders, channel stuffing.', 'Very high for growth stocks.', '简单说，公司卖得更多、增长更快，通常是好事。但也要看它是不是为了增长牺牲利润。'),
  ('RULE 004', 'Earnings and Revenue', 'Revenue slowdown', 'Usually negative.', 'Negative if it reflects weaker demand, stronger competition, or market maturity.', 'Revenue growth, market share, operating margin, terminal growth, valuation multiple.', 'Lower revenue growth forecasts reduce future cash flow and may lower terminal growth assumptions.', 'Revenue slowdown makes investors reassess the company''s growth story, especially for high-valuation growth stocks.', 'Competition, demand saturation, weaker pricing power.', 'High if user bought the stock for growth.', '简单说，公司增长变慢了，市场会担心它以后赚不到之前预期那么多钱。'),
  ('RULE 005', 'Earnings and Revenue', 'Guidance upgrade', 'Usually positive.', 'Positive if the upgrade reflects sustainable business improvement.', 'Revenue forecast, margin forecast, EPS, free cash flow, valuation multiple.', 'Future forecasts may be raised, increasing DCF value.', 'Management guidance upgrade suggests higher confidence in future performance.', 'Over-optimistic guidance, macro reversal, one-off drivers.', 'High if the user''s thesis depends on management execution.', '简单说，公司自己说未来可能比原来预期更好，通常是好消息。但要看它有没有能力做到。'),
  ('RULE 006', 'Earnings and Revenue', 'Guidance downgrade', 'Usually negative.', 'Negative if downgrade reflects structural weakness.', 'Revenue forecast, margin forecast, EPS, FCF, valuation multiple.', 'Future cash flow forecasts may be lowered, reducing valuation.', 'A guidance downgrade is often more serious than a single earnings miss because it affects future expectations.', 'Repeated downgrades, management credibility loss, investor confidence decline.', 'High if user''s thesis depends on recovery or growth.', '简单说，公司自己承认未来可能没之前想得好，所以市场通常会比较担心。'),
  ('RULE 007', 'Margin and Costs', 'Gross margin improvement', 'Positive.', 'Positive if sustainable.', 'Gross margin, operating margin, FCF, ROIC.', 'Higher margins increase operating profit and future FCF.', 'Gross margin improvement may reflect pricing power, better product mix, lower input costs, or scale efficiency.', 'Temporary cost benefit, accounting classification changes, price hikes reducing volume.', 'High if margin recovery is part of the investment thesis.', '简单说，公司每卖 1 块钱能留下更多钱了，这是好信号。'),
  ('RULE 008', 'Margin and Costs', 'Gross margin pressure', 'Negative.', 'Negative if cost pressure or price competition persists.', 'Gross margin, operating margin, FCF, EPS.', 'Lower margins reduce future cash flow and valuation.', 'Margin pressure may come from higher input costs, discounts, competition, or supply chain issues.', 'Inability to pass costs to customers, price war, inventory write-down.', 'High if company has weak pricing power.', '简单说，公司收入可能还在，但成本变高或卖价变低，导致赚钱没以前容易。'),
  ('RULE 009', 'Margin and Costs', 'Operating margin improvement', 'Positive.', 'Positive if driven by efficiency and scale.', 'Operating margin, EBIT, FCF, ROIC.', 'Higher EBIT margin increases after-tax operating profit and FCF.', 'Operating margin improvement suggests better cost control, scale benefits, or stronger pricing power.', 'Cutting important R&D, marketing, or staff to boost short-term margin.', 'High for companies undergoing restructuring.', '简单说，公司不只是卖得多，而是运营得更有效率，赚得更扎实。'),
  ('RULE 010', 'Margin and Costs', 'Operating margin pressure', 'Negative.', 'Negative if persistent.', 'EBIT margin, FCF, valuation multiple, ROIC.', 'Lower EBIT margin reduces future FCF forecasts.', 'Operating margin pressure indicates cost structure deterioration, weaker pricing power, or operating deleverage.', 'Fixed cost pressure, price war, cost inflation.', 'High if user thesis depends on profit recovery.', '简单说，公司赚钱效率变差了。收入可能还行，但扣掉成本后剩下的钱少了。'),
  ('RULE 011', 'Margin and Costs', 'Cost cutting', 'Positive or mixed.', 'Positive if it improves efficiency without hurting growth.', 'Operating expenses, operating margin, FCF, growth capacity.', 'Cost cutting can increase FCF, but excessive cuts may reduce long-term growth.', 'The quality of cost cutting depends on whether management is removing waste or cutting core capabilities.', 'Staff loss, lower product quality, weaker innovation.', 'High if cost discipline is central to the thesis.', '简单说，公司省钱可以提高利润，但如果省过头，影响未来发展，就不一定是好事。'),
  ('RULE 012', 'Margin and Costs', 'Restructuring', 'Mixed or negative.', 'Positive if execution succeeds.', 'One-off costs, operating margin, FCF, execution risk.', 'Short-term FCF may fall due to restructuring costs; long-term value may improve if margins rise.', 'Restructuring is short-term pain for possible long-term gain. The key is whether cost savings are real and sustainable.', 'Execution failure, cost overrun, staff disruption.', 'High if user owns a company in turnaround.', '简单说，公司现在可能要花钱调整业务，所以短期不好看。但如果调整成功，以后可能更省钱、利润更高。'),
  ('RULE 013', 'Cash Flow and Working Capital', 'Operating cash flow stronger than earnings', 'Positive.', 'Positive if sustainable.', 'Operating cash flow, FCF, earnings quality, working capital.', 'Strong cash conversion supports DCF quality.', 'Cash flow stronger than earnings suggests higher earnings quality and strong cash collection.', 'One-off working capital release, delaying supplier payments.', 'High for companies with earnings quality concerns.', '简单说，公司不只是账面赚钱，而是真的收到现金了，这是比较健康的信号。'),
  ('RULE 014', 'Cash Flow and Working Capital', 'Operating cash flow weaker than earnings', 'Negative.', 'Negative if persistent.', 'FCF, working capital, receivables, inventory, earnings quality.', 'Weak cash conversion may require lower FCF forecasts.', 'Profit without cash flow may indicate weak earnings quality, rising receivables, inventory build-up, or aggressive revenue recognition.', 'Bad debts, inventory write-down, revenue quality issues.', 'High if user relies on reported profit.', '简单说，公司账面上赚钱，但真正收到的钱没跟上，这种情况要小心。'),
  ('RULE 015', 'Cash Flow and Working Capital', 'Receivables increase faster than revenue', 'Negative or cautionary.', 'Negative if persistent.', 'Working capital, cash conversion, FCF, credit risk.', 'More cash tied in receivables lowers FCF.', 'Receivables growing faster than revenue may indicate slower customer payment, looser credit policy, or lower revenue quality.', 'Bad debts, aggressive revenue recognition, customer weakness.', 'High if company sells on credit.', '简单说，公司卖出去了东西，但钱还没收回来。收不回来就会变成问题。'),
  ('RULE 016', 'Cash Flow and Working Capital', 'Inventory build-up', 'Mixed or negative.', 'Negative if caused by weak demand.', 'Working capital, gross margin, FCF, inventory write-down risk.', 'Inventory uses cash and may lead to write-downs or discounting.', 'Inventory build-up may be preparation for growth or a sign products are not selling. Compare with revenue growth and inventory turnover.', 'Demand weakness, obsolete stock, margin pressure.', 'High for retailers, manufacturers, hardware, and consumer companies.', '简单说，公司仓库里的货变多了。可能是准备卖更多，也可能是卖不出去，要看原因。'),
  ('RULE 017', 'Cash Flow and Working Capital', 'Working capital deterioration', 'Negative.', 'Negative if persistent.', 'FCF, liquidity, cash conversion cycle, short-term funding need.', 'More cash tied up in working capital lowers FCF.', 'Working capital deterioration means more capital is locked in receivables, inventory, or other operating assets.', 'Liquidity pressure, more borrowing, lower earnings quality.', 'High for companies with tight cash positions.', '简单说，公司赚钱之前需要先垫更多钱进去，现金压力会变大。'),
  ('RULE 018', 'Cash Flow and Working Capital', 'Free cash flow improvement', 'Positive.', 'Positive if sustainable.', 'FCF, reinvestment capacity, debt repayment, dividends, buybacks.', 'FCF is a core input in DCF valuation, so improvement directly supports value.', 'Better FCF means the company has more cash after operating needs and investment spending.', 'Temporary capex cuts, working capital release, underinvestment.', 'High for valuation and shareholder return.', '简单说，公司扣掉必要开支后剩下的钱更多了，这是估值里很重要的好信号。'),
  ('RULE 019', 'Balance Sheet and Leverage', 'Debt increase', 'Mixed.', 'Depends on use of debt and leverage level.', 'Interest expense, leverage, WACC, financial risk, equity value.', 'Debt may lower WACC at moderate levels but excessive debt raises distress risk and cost of equity.', 'Responsible leverage can improve capital efficiency; excessive leverage reduces flexibility.', 'Higher interest rates, refinancing pressure, covenant restrictions, credit downgrade.', 'High for cyclical or leveraged companies.', '简单说，公司借钱不一定坏。如果借钱能赚更多钱，是好事；但债太多，还不起就危险。'),
  ('RULE 020', 'Balance Sheet and Leverage', 'Debt refinancing', 'Positive if interest cost falls or maturity extends.', 'Positive if liquidity risk falls.', 'Interest expense, liquidity risk, WACC, debt maturity.', 'Lower interest cost improves cash flow to equity and lower risk may reduce required return.', 'Refinancing quality depends on new debt cost, maturity, covenants, and market conditions.', 'Higher refinancing cost, short maturity extension, stricter covenants.', 'High if company has near-term debt maturity.', '简单说，公司把旧债换成更便宜或更晚还的新债，通常能减轻压力。'),
  ('RULE 021', 'Balance Sheet and Leverage', 'Credit rating downgrade', 'Negative.', 'Negative if financing costs remain higher.', 'Cost of debt, WACC, liquidity risk, financial flexibility.', 'Higher borrowing cost can reduce FCF and equity value.', 'A downgrade means credit risk is perceived to be higher.', 'Higher bond yields, refinancing difficulty, investor confidence decline.', 'High for debt-heavy companies.', '简单说，市场觉得这家公司借钱风险变高了，以后借钱可能更贵。'),
  ('RULE 022', 'Balance Sheet and Leverage', 'Asset impairment', 'Negative.', 'Depends on whether it reflects real business deterioration.', 'Asset value, ROA, equity book value, investor confidence.', 'Impairment is non-cash, but it may signal lower future cash flows.', 'An impairment means the expected economic benefit of an asset is lower than its carrying value.', 'More impairments, weak capital allocation, demand decline.', 'High if user thesis depends on asset quality.', '简单说，公司承认以前的资产没想象中值钱了。虽然不一定马上花现金，但通常不是好信号。'),
  ('RULE 023', 'Balance Sheet and Leverage', 'Goodwill impairment', 'Negative.', 'Negative if it suggests acquisition failure.', 'Capital allocation quality, ROIC, investor confidence, future cash flow assumptions.', 'Goodwill impairment does not directly affect FCF, but may signal acquired business cash flows are weaker than expected.', 'Goodwill impairment often shows that past acquisition premiums were not justified by future returns.', 'More impairments, poor M&A discipline, falling ROIC.', 'High for acquisitive companies.', '简单说，公司以前买别的公司可能买贵了，现在承认那笔资产没那么值钱。'),
  ('RULE 024', 'Capital Allocation', 'Dividend increase', 'Usually positive.', 'Positive if supported by sustainable FCF.', 'FCF, shareholder return, capital allocation, investor confidence.', 'Dividends do not directly increase firm value, but may signal stronger cash flow and confidence.', 'Dividend increases can indicate financial strength, but the firm must retain enough cash for good investments.', 'Over-distribution, underinvestment, unsustainable dividend.', 'High for income-focused users.', '简单说，公司多分钱给股东，通常说明现金流不错。但如果分太多影响未来发展，也不一定最好。'),
  ('RULE 025', 'Capital Allocation', 'Dividend cut', 'Usually negative.', 'Mixed.', 'FCF, balance sheet strength, investor confidence, cost of equity.', 'DCF is based on FCF, not dividends, but a dividend cut may signal cash flow pressure or reinvestment needs.', 'A dividend cut may indicate weak cash generation, but could be positive if cash is retained to reduce debt or fund high-return projects.', 'Cash flow stress, income investor selling, lower management confidence.', 'High for income-oriented investors.', '简单说，公司少分红会让投资者担心现金不够。但如果是为了还债或投资好项目，长期不一定坏。'),
  ('RULE 026', 'Capital Allocation', 'Share buyback', 'Usually positive.', 'Positive if shares are undervalued and company has excess cash.', 'Shares outstanding, EPS, capital allocation, leverage, per-share value.', 'Buybacks do not directly change enterprise value, but can increase value per share if done below intrinsic value.', 'Buyback quality depends on repurchase price, funding source, and alternative investment opportunities.', 'Overpriced buyback, debt-funded buyback, sacrificing growth investment.', 'High for per-share value.', '简单说，公司买回自己的股票，可能说明它觉得股票便宜。但如果买贵了或借钱买，就不一定好。'),
  ('RULE 027', 'Capital Allocation', 'Equity issuance / capital raising', 'Usually negative.', 'Depends on use of funds.', 'Dilution, shares outstanding, balance sheet, growth investment.', 'Issuance dilutes existing shareholders, but may create long-term value if funds earn high returns.', 'Market often worries about dilution, but the purpose of the capital raise matters.', 'Low-price issuance, cash stress, poor project returns.', 'High for existing shareholders.', '简单说，公司发行更多股票会稀释老股东，所以短期通常不好。但如果这笔钱能带来更高回报，长期可能有帮助。'),
  ('RULE 028', 'Capital Allocation', 'Capex increase', 'Mixed.', 'Positive if investment returns are high.', 'Capex, FCF, revenue growth, ROIC, terminal value.', 'Near-term FCF falls, but future growth and cash flow may rise.', 'Higher capex may be maintenance or growth investment. Growth capex should be judged by expected return.', 'Low returns, delays, cost overruns.', 'High if user thesis depends on expansion.', '简单说，公司现在多花钱建设未来。如果这些投资以后能赚钱，是好事；如果花错了，就是坏事。'),
  ('RULE 029', 'Capital Allocation', 'Capex cut', 'Positive for short-term FCF.', 'Negative if it weakens future growth.', 'FCF, growth capacity, asset quality, competitive position.', 'Short-term FCF rises, but terminal growth may fall.', 'Capex cuts can reflect efficiency or underinvestment.', 'Aging assets, weaker growth, lower competitiveness.', 'High for capital-intensive firms.', '简单说，公司少花钱短期现金流会好看，但如果是削减未来发展投资，长期可能不好。'),
  ('RULE 030', 'Governance and Management', 'CEO change', 'Mixed or negative.', 'Depends on new CEO quality and strategy.', 'Execution risk, investor confidence, valuation multiple, WACC.', 'Does not change cash flow immediately, but may affect future strategy, margins, and capital allocation.', 'Management change increases uncertainty. If prior management performed poorly, a new CEO may improve long-term value.', 'Unclear strategy, talent loss, transition issues.', 'High if management execution is important to user thesis.', '简单说，换 CEO 不会马上让公司赚钱变多或变少，但会让市场不确定。新 CEO 强的话，长期可能是好事。'),
  ('RULE 031', 'Governance and Management', 'CFO resignation', 'Negative or cautionary.', 'Depends on reason and financial transparency.', 'Reporting quality, investor confidence, governance risk.', 'Does not directly affect DCF, but may increase perceived risk and cost of equity.', 'CFO resignation can raise questions about reporting, financing, or internal controls.', 'Accounting problems, internal control weakness, financing pressure.', 'High if company already has reporting concerns.', '简单说，管财务的人突然走了，市场会担心公司财务是不是有问题。'),
  ('RULE 032', 'Governance and Management', 'Governance scandal', 'Negative.', 'Negative if trust, regulation, or reputation is damaged.', 'WACC, valuation multiple, legal cost, reputation.', 'Higher risk may raise discount rate and reduce future revenue or margins.', 'Governance problems reduce investor trust and may create legal, regulatory, and reputational costs.', 'Fines, management change, lawsuits, audit issues.', 'High for all shareholders.', '简单说，公司管理层或治理出问题，市场会担心它不透明、不可靠。'),
  ('RULE 033', 'M&A and Strategy', 'Acquisition', 'Mixed.', 'Depends on price paid, synergies, and integration.', 'Revenue growth, synergies, margin, debt, ROIC, integration risk.', 'Value increases if synergies exceed premium paid. Value falls if the buyer overpays.', 'Acquisitions can create scale and growth, but often destroy value when integration is poor or price is too high.', 'Overpayment, culture clash, debt increase, synergy failure.', 'High if user owns the acquiring company.', '简单说，公司买别的公司不一定好。买得便宜、整合好就是好事；买贵了就是坏事。'),
  ('RULE 034', 'M&A and Strategy', 'Divestiture / asset sale', 'Mixed or positive.', 'Positive if low-return assets are sold and focus improves.', 'ROIC, focus, debt reduction, FCF, revenue base.', 'Revenue may fall, but value may improve if ROIC rises or debt falls.', 'Asset sale quality depends on sale price, asset profitability, and use of proceeds.', 'Selling too cheaply, losing strategic assets, lower revenue.', 'High if company is restructuring.', '简单说，公司卖掉一部分业务，可能是为了更专注或还债。要看卖的是好资产还是拖后腿的资产。'),
  ('RULE 035', 'M&A and Strategy', 'Spin-off', 'Positive or mixed.', 'Positive if it unlocks hidden value.', 'Sum-of-the-parts valuation, management focus, capital allocation.', 'Spin-off may increase valuation multiple by allowing separate businesses to be valued more clearly.', 'Spin-offs can reduce conglomerate discount, but may increase costs and complexity.', 'Loss of scale, standalone financial weakness, execution risk.', 'High if company has multiple business segments.', '简单说，公司把一部分业务拆出来，可能让市场更清楚每块业务值多少钱。'),
  ('RULE 036', 'Macro and Economics', 'Interest rate rise', 'Usually negative for equities.', 'Depends on sector, leverage, and pricing power.', 'WACC, cost of debt, demand, valuation multiple.', 'Higher discount rates reduce present value of future cash flows.', 'Rising rates pressure valuations, especially for high-growth and leveraged companies.', 'Higher financing cost, lower demand, multiple compression.', 'High for growth stocks, REITs, banks, and leveraged companies.', '简单说，利率上升会让钱变贵，也会让未来利润折现后变得没那么值钱。'),
  ('RULE 037', 'Macro and Economics', 'Interest rate cut', 'Usually positive.', 'Depends on why rates are cut.', 'WACC, cost of debt, demand, valuation multiple.', 'Lower discount rates can increase present value of future cash flows.', 'Rate cuts support valuation, but if cuts happen because the economy is weak, fundamentals may still be under pressure.', 'Recession, weak demand, bank margin pressure.', 'High for rate-sensitive sectors.', '简单说，降息一般对股票估值有帮助，但如果是因为经济太差才降息，也不能只看好的一面。'),
  ('RULE 038', 'Macro and Economics', 'Inflation surprise', 'Usually negative.', 'Depends on pricing power.', 'Input cost, pricing power, margin, interest rates, WACC.', 'Higher costs and higher rates can reduce FCF and valuation.', 'Inflation affects cost structure. Companies with pricing power can pass costs to customers.', 'Margin squeeze, further rate hikes, weaker demand.', 'High for consumer, retail, manufacturing, and infrastructure companies.', '简单说，物价涨太快，公司成本会上升。如果公司不能涨价，利润会被挤压。'),
  ('RULE 039', 'Macro and Economics', 'GDP slowdown', 'Usually negative.', 'More negative for cyclical sectors; less negative for defensive sectors.', 'Revenue growth, demand, margin, credit risk.', 'Future revenue and margin forecasts may be reduced.', 'Slower economic growth reduces consumption, investment, and corporate earnings.', 'Demand decline, inventory build-up, credit losses.', 'High for cyclical stocks.', '简单说，经济变慢时，很多公司卖东西会更难，赚钱也可能变少。'),
  ('RULE 040', 'Macro and Economics', 'Currency depreciation', 'Depends on revenue and cost currency exposure.', 'Exporters may benefit; importers may suffer.', 'Revenue translation, input cost, margin, FX risk.', 'Foreign revenue companies may benefit; foreign cost or foreign debt companies may suffer.', 'FX affects revenue translation, cost structure, and debt burden.', 'Poor hedging, foreign debt increase, import cost pressure.', 'High for multinational companies.', '简单说，汇率变化对公司影响不同。赚外币的公司可能受益，花外币或借外币的公司可能受损。'),
  ('RULE 041', 'Sector and Commodity', 'Commodity price increase', 'Positive for producers, negative for consumers.', 'Depends on sustainability.', 'Revenue, input cost, margin, FCF, sector sentiment.', 'Producers may see higher revenue and FCF; users of commodities may see margin pressure.', 'Commodity price changes affect companies differently depending on whether they sell or consume the commodity.', 'Price reversal, cost inflation, policy intervention.', 'High for miners, energy, airlines, manufacturers, and consumer staples.', '简单说，卖铁矿石、石油、黄金的公司通常受益；需要买这些原材料的公司可能成本上升。'),
  ('RULE 042', 'Sector and Commodity', 'Commodity price decline', 'Negative for producers, positive for consumers.', 'Depends on cost curve and demand.', 'Revenue, margin, reserves value, FCF.', 'Resource companies may see lower revenue and cash flow forecasts.', 'Resource company valuations are highly sensitive to commodity price assumptions.', 'Asset impairment, project delays, dividend cuts.', 'High for resource stocks.', '简单说，卖资源的公司会因为价格下跌少赚钱；但买资源当原材料的公司可能会省钱。'),
  ('RULE 043', 'Sector and Commodity', 'Regulatory approval', 'Usually positive.', 'Positive if commercialisation succeeds.', 'Revenue growth, market share, R&D productivity, risk.', 'Risk-adjusted expected future cash flows may increase.', 'Approval reduces regulatory risk and may open a new revenue stream.', 'Weak sales, competition, pricing and reimbursement limits.', 'High for biotech, healthcare, infrastructure, and project-driven companies.', '简单说，公司产品或项目获批通常是好消息，因为它可能带来新收入。但最后还要看卖得好不好。'),
  ('RULE 044', 'Sector and Commodity', 'Regulatory rejection', 'Negative.', 'Severely negative if company depends on the project or product.', 'Pipeline value, revenue growth, R&D value, FCF, risk.', 'Expected cash flows from the product or project may be removed or reduced.', 'Rejection lowers pipeline or project value and may increase costs or delay launch.', 'Project termination, funding need, competitor advantage.', 'High if investment thesis depends on approval.', '简单说，公司本来指望这个产品或项目赚钱，但现在没批下来，所以未来收入预期会下降。'),
  ('RULE 045', 'Risk and External Shock', 'Lawsuit or regulatory investigation', 'Usually negative.', 'Depends on fines, restrictions, and reputation damage.', 'Legal cost, revenue risk, margin, WACC, valuation multiple.', 'Potential fines and business restrictions can reduce cash flow and increase risk premium.', 'Legal and regulatory events increase uncertainty and may cause markets to discount worst-case outcomes.', 'Fines, business restrictions, customer loss, management change.', 'High for all shareholders, especially concentrated positions.', '简单说，公司被起诉或调查，市场会担心它要赔钱、被罚，或者以后做生意受影响。'),
  ('RULE 046', 'Risk and External Shock', 'Cybersecurity breach', 'Negative.', 'Negative if trust, customer retention, or regulation is affected.', 'Legal cost, reputation, revenue retention, capex, opex.', 'Future costs may increase and customer retention may decline.', 'Data breaches create legal, operational, and reputational risks.', 'Regulatory fines, customer loss, repair costs, lawsuits.', 'High for banks, healthcare, technology, and consumer platforms.', '简单说，公司数据出事了，可能要赔钱，也可能让客户不再信任它。'),
  ('RULE 047', 'Risk and External Shock', 'Supply chain disruption', 'Negative.', 'Depends on alternative suppliers and inventory buffer.', 'Revenue, gross margin, working capital, delivery timing.', 'Revenue may be delayed, costs may rise, and short-term FCF may fall.', 'Supply chain issues affect production, delivery, cost, and customer satisfaction.', 'Shortages, higher costs, lost customers, order cancellation.', 'High for manufacturers, retailers, hardware, and automotive companies.', '简单说，公司可能没法按时生产或交货，所以收入和利润都会受影响。'),
  ('RULE 048', 'Portfolio Risk', 'High position concentration', 'Increases portfolio risk.', 'Higher idiosyncratic risk and drawdown risk.', 'Portfolio volatility, stock-specific risk, drawdown risk.', 'Does not affect company DCF, but affects user portfolio risk.', 'A concentrated position makes the portfolio highly sensitive to one company''s news.', 'Large loss if one company has negative event.', 'Very high if one stock exceeds a large portfolio weight.', '简单说，如果你把太多钱放在一只股票上，这家公司一出事，你整个组合都会很痛。'),
  ('RULE 049', 'Portfolio Risk', 'Sector concentration', 'Increases sensitivity to sector news.', 'Sector cycle can dominate portfolio performance.', 'Portfolio beta, sector exposure, correlation, drawdown risk.', 'Does not affect individual company DCF, but affects portfolio risk structure.', 'Owning many stocks in one sector may still mean poor diversification.', 'Industry regulation, sector demand shock, commodity cycle.', 'High if several holdings belong to one sector.', '简单说，你可能买了很多只股票，但如果它们都属于同一个行业，其实没有真正分散风险。'),
  ('RULE 050', 'Portfolio Risk', 'High beta portfolio', 'Outperforms in rising markets and underperforms in falling markets.', 'Higher systematic risk requires higher expected return.', 'Systematic risk, cost of equity, volatility.', 'Higher beta can increase cost of equity and make valuation more sensitive.', 'Beta measures sensitivity to broad market movement.', 'Market selloff, rate increase, risk-off sentiment.', 'High if portfolio is dominated by high-growth or cyclical stocks.', '简单说，高 beta 股票像加速器，市场好时涨得快，市场差时也可能跌得更狠。')
on conflict (rule_id) do update set
  category = excluded.category,
  event_type = excluded.event_type,
  typical_short_term_impact = excluded.typical_short_term_impact,
  typical_long_term_impact = excluded.typical_long_term_impact,
  affected_valuation_drivers = excluded.affected_valuation_drivers,
  dcf_valuation_implication = excluded.dcf_valuation_implication,
  professional_logic = excluded.professional_logic,
  key_risks = excluded.key_risks,
  portfolio_relevance = excluded.portfolio_relevance,
  beginner_friendly_summary = excluded.beginner_friendly_summary;
